name: CI pipeline

on:
  pull_request:
  push:
    branches:
      - 30-review-overview-on-github-actions-and-complete-the-following-tasks

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
        
      - name: Run Ruff Linter
        run: |
          ruff check --exclude=ecommerce/settings --exclude=store/migrations --fix
          ruff format --exclude=store/migrations store ecommerce
